---
title: "analysis"
output: html_document
date: "2025-03-03"
---

# Install packages

```{r}
install.packages("tidyverse", "naniar")
```

# Load libraries

```{r}
library(tidyverse)
library(naniar)
```

# Themes

```{r}
theme <- theme_bw() + 
         theme(plot.title = element_text(face = "bold", size = 11),
               strip.background = element_rect(fill = "white", linewidth = 0.5),
               strip.text = element_text(face = "bold", colour = "black"),
               legend.position = "right", legend.justification = "left")
```


# Import table

```{r}
# Study patients
patients_list <- read.csv(paste0(path, "clad-bal-multiomics-bm2/analysis/backup/clinical-metadata/patients-selection.csv") )
stable_patients <- patients_list %>% filter(Enrolled.in.stable.study == TRUE) %>% pull(Record.ID)
length(stable_patients) # 56
biomarker_patients <- patients_list %>% filter(Enrolled.in.biomarker.study == TRUE) %>% pull(Record.ID)
length(biomarker_patients) # 26
```

Patient 11 changed pred/mmf date from 11/01/2018 to 11/01/2019 as the date did not make sense
Patient 44 changed pulse date from 07/02/2019 to 07/12/2019 to be consistent with following pulse dates

```{r}
sheet_names <- readxl::excel_sheets(paste0(path, "immunosuppression-analysis/immunosuppression-table.xlsx"))
xlsx <- readxl::read_xlsx(paste0(path, "immunosuppression-analysis/immunosuppression-table.xlsx"))
#master_metadata <- readRDS(paste0(path, "clad-bal-multiomics-bm2/clinical_metadata_formatting/rsd_files/master_metadata.rds"))
#clad_assessment <- readRDS(paste0(path, "clad-bal-multiomics-bm2/clinical_metadata_formatting/rsd_files/clad_assessment.rds"))

# Extract each sheet
table_list <- list()
for (i in sheet_names){
  table_list[[i]] <- readxl::read_xlsx(paste0(path, "immunosuppression-analysis/immunosuppression-table.xlsx"), sheet = i ) %>%
    mutate(Record.ID = i,
           Record.ID = as.numeric(gsub("ID", "", Record.ID)) ) %>%
    replace_with_na_all(condition = ~.x %in% "<NA>")
}

table <- bind_rows(table_list) %>%
  left_join(master_metadata$general_metadata[, c("Record.ID", "transplant_date")] ) %>%
  left_join(clad_assessment[, c("Record.ID", "clad_clinical", "clad_day_clinical")]) %>%
  mutate(Group = ifelse(clad_clinical == TRUE, "CLAD", "CLAD-free")) %>%
  left_join(patients_list[, c("Record.ID", "Enrolled.in.stable.study", "Enrolled.in.biomarker.study")]) %>%
  filter(Enrolled.in.stable.study == TRUE | Enrolled.in.biomarker.study == TRUE) %>%
  mutate(Group = factor(Group, levels = c("CLAD-free", "CLAD")),
         Study = ifelse(Group == "CLAD-free" & Enrolled.in.stable.study == TRUE & Enrolled.in.biomarker.study == TRUE, "Stable &\nBiomarker",
                        ifelse(Group == "CLAD-free" & Enrolled.in.stable.study == TRUE & Enrolled.in.biomarker.study == FALSE, "Stable",
                               ifelse(Group == "CLAD" & Enrolled.in.biomarker.study == TRUE, "Biomarker", NA))),
         Study = factor(Study, levels = c("Stable", "Stable &\nBiomarker", "Biomarker")) ) 

table %>% filter(!Study %in% "Stable") %>% group_by(Group) %>% count(Record.ID)
# Biomarker cohort: all 13 CLAD present, all 13 CLAD-free present, 
# Stable cohort: 21 CLAD-free from present
```


```{r}
# Split into sub tables accordingly
tacro_df <- table %>%
  dplyr::select(Record.ID, transplant_date, Group, clad_day_clinical, Study, tacrolimus_date, tacrolimus_level, tacro_check) %>%
  filter(!is.na(tacrolimus_level)) %>%
  mutate(tacrolimus_level = gsub("* ", "", tacrolimus_level, fixed = TRUE),
         tacrolimus_level = gsub("<", "", tacrolimus_level),
         tacrolimus_level = as.numeric(gsub("(c) ", "", tacrolimus_level, fixed = TRUE)),
         tacrolimus_date = as.Date(tacrolimus_date),
         Days = as.numeric(tacrolimus_date - transplant_date)) %>%
  filter(Days <= 900, Study != "Stable")
  
prednisolone_df <- table %>%
  dplyr::select(Record.ID, transplant_date, Group, clad_day_clinical, Study, prednisolone_date, prednisolone_dose_mgd) %>%
  filter(!is.na(prednisolone_dose_mgd)) %>%
  mutate(prednisolone_date = as.Date(prednisolone_date),
         Days = as.numeric(prednisolone_date - transplant_date)) %>%
  filter(Days <= 900, Study != "Stable")
  
mmf_df <- table %>%
  dplyr::select(Record.ID, transplant_date, Group, clad_day_clinical, Study, mmf_date, mmf_dose_gd) %>%
  filter(!is.na(mmf_dose_gd)) %>%
  mutate(mmf_date = as.Date(mmf_date),
         Days = as.numeric(mmf_date - transplant_date))
  
azathioprine_df <- table %>%
  dplyr::select(Record.ID, transplant_date, Group, clad_day_clinical, Study, azathioprine_date, azathioprine_dose_mgd) %>%
  filter(!is.na(azathioprine_dose_mgd)) %>%
  mutate(azathioprine_date = as.Date(azathioprine_date),
         Days = as.numeric(azathioprine_date - transplant_date))
  
everolimus_df <- table %>%
  dplyr::select(Record.ID, transplant_date, Group, clad_day_clinical, Study, everolimus_date, everolimus_level_mcgl) %>%
  filter(!is.na(everolimus_level_mcgl)) %>%
  mutate(everolimus_level_mcgl = as.numeric(gsub("* ", "", everolimus_level_mcgl, fixed = TRUE)),
         everolimus_date = as.Date(everolimus_date),
         Days = as.numeric(everolimus_date - transplant_date))

cyclosporin_df <- table %>%
  dplyr::select(Record.ID, transplant_date, Group, clad_day_clinical, Study, cyclosporin_date, cyclosporin_level) %>%
  filter(!is.na(cyclosporin_level)) %>%
  mutate(cyclosporin_level = as.numeric(gsub("* ", "", cyclosporin_level, fixed = TRUE)),
         cyclosporin_date = as.Date(cyclosporin_date),
         Days = as.numeric(cyclosporin_date - transplant_date))
  
weight_df <- table %>%
  dplyr::select(Record.ID, transplant_date, Group, clad_day_clinical, Study, weight_date, weight)  %>%
  filter(!is.na(weight)) %>%
  mutate(weight_date = as.Date(weight_date),
         Days = as.numeric(weight_date - transplant_date))
  
pulse_df <- table %>%
  dplyr::select(Record.ID, transplant_date, Group, clad_day_clinical, Study, pulse_date, pulse_dose) %>%
  filter(!is.na(pulse_dose)) %>%
  mutate(pulse_date = as.Date(pulse_date),
         Days = as.numeric(pulse_date - transplant_date)) %>%
  filter(Days <= 900, Study != "Stable")

d <- pulse_df
```

```{r}
# Tacrolimus levels over time post-transplant
ggplot(tacro_df, aes(x = Days, y = tacrolimus_level)) +
  geom_smooth(aes(group = Group, colour = Group)) +
  labs(title = "Tacrolimus", y = "Trough value") +
  theme +
  scale_y_log10() +
  facet_wrap(~Record.ID) +
  scale_colour_manual(values = c("CLAD" = "orange", "CLAD-free" = "darkgrey"))

# Prednisolone
ggplot() +
  geom_smooth(data = prednisolone_df, aes(x = Days, y = prednisolone_dose_mgd, group = Group, colour = Group)) +
  geom_point(data = pulse_df, aes(x = Days, y = pulse_dose), colour = "red") +
  geom_point(data = clad_assessment %>% filter(Record.ID %in% unique(prednisolone_df$Record.ID)), aes(x = clad_day_clinical, y = 1), shape = 4) +
  labs(title = "Prednisolone", y = "Dose (mg/d)") +
  theme +
  scale_y_log10() +
  facet_wrap(~Record.ID) +
  scale_colour_manual(values = c("CLAD" = "orange", "CLAD-free" = "darkgrey"))


```





